# Generated by Django 3.0.6 on 2020-06-18 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addstudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('roll_number', models.CharField(max_length=25, unique=True)),
                ('course', models.CharField(max_length=20)),
                ('past_Experience', models.CharField(max_length=256)),
            ],
        ),
    ]
