# Generated by Django 3.0.6 on 2020-06-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200618_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addstudent',
            name='email_id',
        ),
        migrations.RemoveField(
            model_name='addstudent',
            name='past_Experience',
        ),
        migrations.AddField(
            model_name='addstudent',
            name='course',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
