# Generated by Django 3.0.6 on 2020-06-18 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_addstudent_email_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='addstudent',
            name='past_experiences',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
